### ISSUE TITLE
Add constraints

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#296]
Hi,
I wamt to add AEP as a constraint or another contraints.
What should I do?

**Comment by gbarter** [comment]
@SeongwooCheon This is a good idea and I have tried to implement it in a feature branch.  If you are comfortable doing so, please checkout the `aep_constr` branch and give it a try.  If you are using the yaml files, there is now an AEP option in the analysis_options.yaml file:
```
...
constraints:
    blade:
        AEP:
            flag: True
            min: 1.1234e7 # Minimum value in kWh
...
```
