### ISSUE TITLE
add design variables

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#297]
Hi

I want to add design variables, te_ss and te_ps. so I modified te_ss(te_ps) flag into True in the analysis_options_struct.yaml. but An error has occurred.

I think that I need to add te_ss, te_ps in the modeling_options.yaml. but geometry file,BAR0.yaml,do not contain te_ss, te_ps, just TE_reinforcement. 
Do I have to divide the TE_reinforcement into ss part, ps part?

And, I want to add layer thickness as design variables like LE_reinforcement, TE_ps_filler etc.
Can I refer to your answer? : https://github.com/WISDEM/WISDEM/issues/283

thank you

**Comment by gbarter** [comment]
Hi again,

If you want to active the TE reinforcements as a design variable, then your analysis_options file would contain:
```
        structure:
            spar_cap_ss:
                flag: True             # Flag to optimize the spar cap thickness on the suction side
                n_opt: 4               # Number of control points along blade span
                max_decrease: 0.7      # Maximum nondimensional decrease at the n_opt locations
                max_increase: 1.3      # Maximum nondimensional increase at the n_opt locations
                index_start: 1         # Lock the first DV from blade root
                index_end: 3           # The last DV at blade tip is locked
            spar_cap_ps:
                flag: True             # Flag to optimize the spar cap thickness on the pressure side
                equal_to_suction: True # Flag to impose the spar cap thickness on pressure and suction sides equal
                n_opt: 4               # Number of control points along blade span
                max_decrease: 0.7      # Maximum nondimensional decrease at the n_opt locations
                max_increase: 1.3      # Maximum nondimensional increase at the n_opt locations
                index_start: 1         # Lock the first DV from blade root
                index_end: 3           # The last DV at blade tip is locked
            te_ss:
                flag: True             # Flag to optimize the spar cap thickness on the suction side
                n_opt: 4               # Number of control points along blade span
                max_decrease: 0.7      # Maximum nondimensional decrease at the n_opt locations
                max_increase: 1.3      # Maximum nondimensional increase at the n_opt locations
                index_start: 1         # Lock the first DV from blade root
                index_end: 3           # The last DV at blade tip is locked
            te_ps:
                flag: True             # Flag to optimize the spar cap thickness on the pressure side
                n_opt: 4               # Number of control points along blade span
                max_decrease: 0.7      # Maximum nondimensional decrease at the n_opt locations
                max_increase: 1.3      # Maximum nondimensional increase at the n_opt locations
                index_start: 1         # Lock the first DV from blade root
                index_end: 3           # The last DV at blade tip is locked
```

If you want to make design variables out of other layers, then generally yes the answer you referred to would work.  I would expect some errors and debugging.  My suggestion would be to start with the LE reinforcement first before tackling an arbitrary layer.
