### ISSUE TITLE
How to use inverse design to reconfiguration a inputs from wind_speed-power_curve-thrust_curve?

### ISSUE THREAD

**Issue by WANG-KUI-TJU** [WISDEM/WISDEM#587]
## Description
 I'm currently facing an engineering challenge: the wind turbine manufacturers only provide thrust curves, power curves, and some basic mass inertia parameters. I need to use these parameters (outputs) to infer a series of input parameters in order to apply these turbine parameters to the design of the floating structure. I'm currently doing this by modifying publicly available reference turbines, such as the [IEA-15MW](https://github.com/IEAWindTask37/IEA-15-240-RWT).The aerodynamic part is essentially a multi-objective optimization problem. It uses curves (such as thrust curves) to constrain it, and changes chord length, blade length, and twist angle to meet the constraints. I saw an introduction to optimization in the example `16_inverse_design`, but I still don't understand how to do it. I would greatly appreciate it if you could provide assistance.

**Comment by ptrbortolotti** [comment]
Have you already looked at the documentation about example 16?

https://wisdem.readthedocs.io/en/master/examples/16_inverse_design/tutorial.html

**Comment by WANG-KUI-TJU** [comment]
> Have you already looked at the documentation about example 16?
> 
> https://wisdem.readthedocs.io/en/master/examples/16_inverse_design/tutorial.html

yes,I have already looked the documentation [rotor design part](https://wisdem.readthedocs.io/en/master/examples/16_inverse_design/tutorial.html),the constraints of the example are mass and frequency. I checked code of `glue_code\gc_PoseOptimization.py`.I noticed the variables `match_cl_cd` and `rated velocity`、`thrust_coeff` and so on, but I'm not sure how they are defined and inputted. I'm not sure which variables I should choose to inverse  power curve and thrust curve. I might need to look further into the code for their definitions and usage. If you could provide any information or assistance, I would greatly appreciate it.

**Comment by WANG-KUI-TJU** [comment]
I noticed that there are some discrepancies between the text and the code in [3a. Blade Optimization Example](https://wisdem.readthedocs.io/en/master/examples/03_blade/tutorial.html). For example, in the code, `maximum: 11`, while the text describes it as `TSR is allowed to vary between 8 and 10`. The description in the code is `index_end: 3` and the description in the text is `so set n_opt to 8 and index_end to 7.` Although this might not matter to experienced users, it could be misleading for beginners who want to follow along step by step.

**Comment by ptrbortolotti** [comment]
hello again, thanks for spotting that inconsistency in the documentation of example 3. 
as for your other questions, the full truth is that we work with industrial partners to help them perform what you are trying to do here. if that's a possibility for you, please email us directly (link)[https://research-hub.nrel.gov/en/persons/pietro-bortolotti]
If you this is not possible for you, I'm afraid you will need to become familiar with the code and expand example 16 to account for your own figures of merit and constraints. you might need to combine different examples to achieve a full turbine design

**Comment by WANG-KUI-TJU** [comment]
> hello again, thanks for spotting that inconsistency in the documentation of example 3. as for your other questions, the full truth is that we work with industrial partners to help them perform what you are trying to do here. if that's a possibility for you, please email us directly ([link](https://research-hub.nrel.gov/en/persons/pietro-bortolotti)) If you this is not possible for you, I'm afraid you will need to become familiar with the code and expand example 16 to account for your own figures of merit and constraints. you might need to combine different examples to achieve a full turbine design

Unfortunately, I don't have that part of the budget,  I will still do my best to familiar with the code and function.

**Comment by gbarter** [comment]
I'll chime in with some steps to take to modify a reference turbine that is a "near-neighbor" of an OEM commercial turbine by re-optimizing around the given specifications:

1. Copy the WindIO geometry-yaml of the reference turbine to a new file and adjust the high level parameters, such as rated power, turbine class, rotor diameter, hub height, gear ratio (if any), and any other key piece of information you might have.  Google searches (or ChatGPT questions) can sometimes reveal component masses or other parameters you might not know or have been provided.  It might also be worthwhile to simplify some of the drivetrain components if there are detailed descriptions in the reference turbine file
2. Optimize your blade planform for Cp or AEP.  Key `analysis_options` inputs would be:
```
design_variables:
    blade:
        aero_shape:
            twist: {flag: false, inverse: true, inverse_target: max_efficiency, n_opt: 10, max_decrease: 0.08722222222222221, max_increase: 0.08722222222222221, index_start: 2, index_end: 10, cap_twist_root: 0.349}
            chord: {flag: true, n_opt: 10, max_decrease: 0.4, max_increase: 1.5, index_start: 1, index_end: 10}
constraints:
    blade:
        stall: {flag: true, margin: 0.12}
        chord: {flag: true, max: <some value>}
        chord_slope: {flag: true}
        rated_velocity: {flag: false, target: <some value from power curve>, acceptable_error: 0.1}
        rated_thrust: {flag: false, target: <some value from power curve>, acceptable_error: 1000.0}
```
3. Then optimize for your blade structure.  An example might be:
```
design_variables:
    blade:
        structure:
           -  {layer_name: Shell_skin, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 2, index_end: 8}
           -  {layer_name: Spar_Cap_SS, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
           -  {layer_name: Spar_Cap_PS, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
           -  {layer_name: LE_reinforcement, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
           -  {layer_name: TE_reinforcement_SS, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
           -  {layer_name: TE_reinforcement_PS, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
```
4.  Optimize your tower, following Example 05


Eventually, the NREL team here may make public our scripts that walk through the above procedure, but we aren't quite ready for that yet.

**Comment by WANG-KUI-TJU** [comment]
> I'll chime in with some steps to take to modify a reference turbine that is a "near-neighbor" of an OEM commercial turbine by re-optimizing around the given specifications:
> 
> 1. Copy the WindIO geometry-yaml of the reference turbine to a new file and adjust the high level parameters, such as rated power, turbine class, rotor diameter, hub height, gear ratio (if any), and any other key piece of information you might have.  Google searches (or ChatGPT questions) can sometimes reveal component masses or other parameters you might not know or have been provided.  It might also be worthwhile to simplify some of the drivetrain components if there are detailed descriptions in the reference turbine file
> 2. Optimize your blade planform for Cp or AEP.  Key `analysis_options` inputs would be:
> 
> ```
> design_variables:
>     blade:
>         aero_shape:
>             twist: {flag: false, inverse: true, inverse_target: max_efficiency, n_opt: 10, max_decrease: 0.08722222222222221, max_increase: 0.08722222222222221, index_start: 2, index_end: 10, cap_twist_root: 0.349}
>             chord: {flag: true, n_opt: 10, max_decrease: 0.4, max_increase: 1.5, index_start: 1, index_end: 10}
> constraints:
>     blade:
>         stall: {flag: true, margin: 0.12}
>         chord: {flag: true, max: <some value>}
>         chord_slope: {flag: true}
>         rated_velocity: {flag: false, target: <some value from power curve>, acceptable_error: 0.1}
>         rated_thrust: {flag: false, target: <some value from power curve>, acceptable_error: 1000.0}
> ```
> 
> 3. Then optimize for your blade structure.  An example might be:
> 
> ```
> design_variables:
>     blade:
>         structure:
>            -  {layer_name: Shell_skin, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 2, index_end: 8}
>            -  {layer_name: Spar_Cap_SS, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
>            -  {layer_name: Spar_Cap_PS, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
>            -  {layer_name: LE_reinforcement, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
>            -  {layer_name: TE_reinforcement_SS, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
>            -  {layer_name: TE_reinforcement_PS, n_opt: 8, max_decrease: 0.2, max_increase: 5.0, index_start: 1, index_end: 7}
> ```
> 
> 4. Optimize your tower, following Example 05
> 
> Eventually, the NREL team here may make public our scripts that walk through the above procedure, but we aren't quite ready for that yet.

Thank you very much for your patient and detailed response. It has been a great help to me, and I now feel more confident in completing this task.I think I roughly understand what you're saying, but I still have some questions. I look forward to your response.
1. If I constrain the rated wind speed and rated thrust, and use $C_p$ as the optimization target, the software defaults to maximizing $C_p$ at 5 m/s. It does not calculate the rated speed and pitch angle needed for rated conditions. How is the rated thrust calculated? Is this data defined in the "control" section of the "turbine.yaml" file?
2. In fact, results are needed for several wind speeds, not just one, to match the target thrust values. That is, for different wind speeds (ws1, ws2), the calculated thrust $T^c$ should match the target thrust $T^t$. 
Our optimization parameters are chord length and twist angle, and the optimization goal is 
_Minimum_ **${ (T_{ws1}^c - T_{ws1}^t)^2 + (T_{ws2}^c - T_{ws2}^t)^2 + (T_{ws3}^c - T_{ws3}^t)^2 + ... + (maybe N) }$**
However, the current optimization targets seem to be limited to Cp, AEP, and some simple customizations. According to the above optimization, we can only satisfy the rated thrust, not the thrust at other wind speeds, so does it need constant adjustment?

**Comment by gbarter** [comment]
Thank you for your holiday well wishes.  Replies may be slower over the next couple of weeks.  Hope you also enjoy your holidays.

1. We also have had mixed results using rated velocity as a design constraint.  It may just be too tough to guide the blade design with an that is so sensitive.  You can try removing that as a constraint.  Other parameters that haven't been mentioned yet are TSR ([example](https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/IEA-15-240-RWT.yaml#L989)), max tip speed ([example](https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/IEA-15-240-RWT.yaml#L979)), and peak thrust shaving ([example](https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/IEA-15-240-RWT.yaml#L983)).  We find that once we have a good handle on those parameters, and specify a rated thrust value, the rest of the power curve generally falls in line.  What type of turbine are you trying to model?  Offshore/onshore?  Power rating?  We can suggest some likely values for those parameters if you don't have them already.
2. WISDEM cannot currently match a vector of power and thrust values in the performance curve as a constraint.  Right now, it is just the single values at rated conditions.  As mentioned above, we find that if we nail down a few key parameters, the rest generally falls in line.  OpenMDAO certainly accepts vector-valued constraints, and many of our structural constraints are vector-valued, so it is just a matter of making the effort for implementation.  If you feel comfortable enough in WISDEM (now or in the future), you could give this a shot.
3. The most common design variables, objectives, and constraints are available in the `analysis_options` file and internally WISDEM links them to the full OpenMDAO driven namespace. See some examples [here](https://github.com/WISDEM/WISDEM/blob/master/wisdem/glue_code/gc_PoseOptimization.py#L666) and [here](https://github.com/WISDEM/WISDEM/blob/master/wisdem/glue_code/gc_PoseOptimization.py#L1024).  While the number of design variables and constraints available in the analysis options file are extensive, there is allowance for user-specified DVs and constraints as described in [Example 11](https://wisdem.readthedocs.io/en/master/examples/11_user_custom/tutorial.html).  Hopefully this helps clarify the confusion.
4. You will have to explain a bit more what modeling options you are looking at.

**Comment by WANG-KUI-TJU** [comment]
Thanks again for your patient answer, I will describe my problem carefully
### Background
In the current floating project, wind turbine manufacturers only provide broad parameters such as thrust curves, power curves, and mass distribution. When designing the floating foundation, turbine parameters are needed as load inputs. Therefore, I need to reverse-engineer these turbine parameters to use as inputs, ensuring that the thrust at different wind speeds matches what the manufacturer provides.To achieve this goal, I will select a similar publicly available turbine as a reference and modify its parameters accordingly.Since the target turbine and the reference turbine are of the same class, most of their parameters are identical. The problem is now simplified to adjusting the chord length and twist angle to align the thrust and power curves of the two turbines.
![power](https://github.com/user-attachments/assets/18d2e9dc-6b4f-461b-9f7a-875ba547b6cc)
![thrust](https://github.com/user-attachments/assets/1a00fb8e-1cad-476d-885e-b594dc601be8)
### Action
#### `IEA-15-240-RWT_modified.yaml`
Since my target wind turbine speed is 8.4 rpm, I set the `control-supervisory-maxTS:106` in the file (approximately $\omega \times r = 0.8797 \times 120\$ ).Then i set `control-torque-tsr:10` （approximately $\frac{\omega \times r}{\text{ratedVelocity}} = \frac{0.8797 \times 120}{\text{11}}$
）and `VS_minspd:0.47124` (4.5rpm) and `VS_minspd:0.87965` (8.4rpm).
```
control:
    supervisory:
        Vin: 3.0
        Vout: 25.0
        maxTS: 106
    pitch:
        PC_zeta: 1.0                      # Pitch controller desired damping ratio [-]
        PC_omega: 0.2                     # Pitch controller desired natural frequency [rad/s]
        ps_percent: 0.8                   # Percent peak shaving  [%, <= 1 ], {default = 80%}
        max_pitch: 1.57                     # Maximum pitch angle [rad], {default = 90 degrees}
        max_pitch_rate: 0.03490658503988659 # 2 deg/s
        min_pitch: 0.                     # Minimum pitch angle [rad], {default = 0 degrees}
    torque:
        control_type: tsr_tracking
        tsr: 10
        max_torque_rate: 1500000.
        VS_minspd: 0.47124     # Minimum rotor speed [rad/s], {default = 0 rad/s}  4.5rpm
        VS_maxspd: 0.87965     # Minimum rotor speed [rad/s], {default = 0 rad/s} 8.4rpm
        VS_zeta: 1.0                      # Torque controller desired damping ratio [-]
        VS_omega: 0.2                     # Torque controller desired natural frequency [rad/s]
```
#### `modeling_options_modified.yaml`
This yaml seems to ensure the activation and deactivation of certain modules. I have enabled all of them, and its content is as follows:
```
General:
    verbosity: False  
WISDEM:
    RotorSE:
        flag: True
    DriveSE:             
        flag: True
    TowerSE:             
        flag: True
    BOS:                 
        flag: True
```
#### `analysis_options_modified.yaml`
According to expectations, I should only need to modify the chord  and twist  to meet my requirements. Therefore, I set the chord length and twist angle as variables and use `rotorse.rp.powercurve.rated_T` as a constraint for optimization，The target value of thrust is _2036000 N_.
```
design_variables:
    blade:
        aero_shape:
            twist:
                flag: True 
                n_opt: 10 
                max_decrease: 0.0872222 
                max_increase: 0.0872222 
                index_start: 2 
                index_end: 10
            chord:
                flag: True  
                n_opt: 10     
                max_decrease: 0.4
                max_increase: 2. 
                index_start: 0 
                index_end: 9 

# figure of merit
merit_figure: Cp

# constraints
constraints:
    blade:
        chord:
            flag: True 
            max: 5 
        chord_slope:
            flag: True 
    user:
      - name: rotorse.rp.powercurve.rated_T
        lower: [2050000]
        upper: [2030000]
        ref: [2036000]
            

# driver
driver:
    optimization:
        flag: True         
        tol: 1.e-6          
        max_iter: 5         
        solver: SLSQP       
        step_size: 1.e-3    
        form: forward       

recorder:
    flag: True              
    file_name: log_opt.sql  
```

**Comment by WANG-KUI-TJU** [comment]
### Some descriptions and code in [Example 3](https://wisdem.readthedocs.io/en/master/examples/03_blade/tutorial.html) do not match, which may cause confusion
- 1
Description : We don’t optimize chord at blade tip (BEM isn’t good at it), so set n_opt to 8 and index_end to 7.
Code:
```
            chord:
                flag: True  # Flag to optimize the chord
                n_opt: 4     # Number of control points along blade span
                max_decrease: 0.4 # Minimum multiplicative gain on existing chord at the n_opt locations
                max_increase: 2. # Maximum multiplicative gain on existing chord at the n_opt locations
                index_start: 1 # Lock the first DVs from blade root
                index_end: 3 # Lock the last DV at blade tip
```
- 2
Description :We set a target stall margin using the same flag type of setting,
Code:
```
        stall:
            flag: False # Constraint on minimum stall margin
            margin: 0.1 # Value of minimum stall margin in [rad]
```

**Comment by WANG-KUI-TJU** [comment]
when my code is
```
design_variables:
    blade:
        aero_shape:
            twist:
                flag: False 
                n_opt: 10 
                inverse: True
                inverse_target: 'max_efficiency'
                max_decrease: 0.08722222222222221
                max_increase: 0.08722222222222221
                index_start: 2
                index_end: 10
            chord:
                flag: True  
                n_opt: 10   
                max_decrease: 0.4
                max_increase: 1.5
                index_start: 1
                index_end: 10

# figure of merit
merit_figure: AEP

# constraints
constraints:
    blade:
        chord:
            flag: True 
            max: 8 
        chord_slope:
            flag: True 
        stall:
            flag: True # Constraint on minimum stall margin
            margin: 0.1 # Value of minimum stall margin in [rad]
    user:
      - name: rotorse.rp.powercurve.rated_T
        lower: [2036000]
        upper: [2050000]
        ref: [2036000]
      - name: rotorse.rp.powercurve.rated_Omega
        lower: [8.30]
        upper: [8.50]
        ref: [8.40]
            

# driver
driver:
    optimization:
        flag: True         
        tol: 1.e-6        
        max_iter: 100        
        solver: SLSQP       
        step_size: 1.e-3    
        form: forward       

recorder:
    flag: True              
    file_name: log_opt.sql  
```
- output is 
```
Positive directional derivative for linesearch    (Exit mode 8)
            Current function value: -75.05602808684819
            Iterations: 12
            Function evaluations: 29
            Gradient evaluations: 8
Optimization FAILED.
Positive directional derivative for linesearch
```

**Comment by ptrbortolotti** [comment]
Most likely your thrust and/or omega constraints are too tight and the optimizer can't satisfy them. Try turning the off (flag set to False) and rerun. Once the optimizer converges, check out the final values of thrust and omega and see how far they are from your target values. An additional complication is that WISDEM computes the rotor speed given the input tip speed ratio and maximum blade tip speed. your optimizer does not have direct control over omega, so enforcing such tight constraint will be problematic. it's a lot easier to set a priori your maximum blade tip speed for your desired omega rather than hoping that the optimizer converges to your target

**Comment by WANG-KUI-TJU** [comment]
> Most likely your thrust and/or omega constraints are too tight and the optimizer can't satisfy them. Try turning the off (flag set to False) and rerun. Once the optimizer converges, check out the final values of thrust and omega and see how far they are from your target values. An additional complication is that WISDEM computes the rotor speed given the input tip speed ratio and maximum blade tip speed. your optimizer does not have direct control over omega, so enforcing such tight constraint will be problematic. it's a lot easier to set a priori your maximum blade tip speed for your desired omega rather than hoping that the optimizer converges to your target

Thank you, I hope you had a great Christmas. I'll try modifying the TSR and maxTS now. Do you know what might be a suitable range for tol and step_size? I saw examples where step_size varies from e-3 to e-6.

**Comment by WANG-KUI-TJU** [comment]
Why are the ref values for AEP and Cp negative, while all the others are positive? Is there something special about this?
```
def set_objective(self, wt_opt):
        # Set merit figure. Each objective has its own scaling.  Check first for user override
        if self.opt["merit_figure_user"]["name"] != "":
            coeff = -1.0 if self.opt["merit_figure_user"]["max_flag"] else 1.0
            wt_opt.model.add_objective(self.opt["merit_figure_user"]["name"],
                                       ref=coeff*np.abs(self.opt["merit_figure_user"]["ref"]))

        elif self.opt["merit_figure"].lower() == "aep":
            wt_opt.model.add_objective("rotorse.rp.AEP", ref=-1.0e6)

        elif self.opt["merit_figure"] == "blade_mass":
            wt_opt.model.add_objective("rotorse.blade_mass", ref=1.0e6)

        elif self.opt["merit_figure"] == "blade_cost":
            wt_opt.model.add_objective("rotorse.total_bc.total_blade_cost", ref=1.0e6)

        elif self.opt["merit_figure"].lower() == "lcoe":
            wt_opt.model.add_objective("financese.lcoe", ref=0.1)

        elif self.opt["merit_figure"] == "blade_tip_deflection":
            wt_opt.model.add_objective("tcons.tip_deflection_ratio")

        elif self.opt["merit_figure"] == "tower_mass":
            wt_opt.model.add_objective("towerse.tower_mass", ref=1e6)

        elif self.opt["merit_figure"] == "tower_cost":
            wt_opt.model.add_objective("tcc.tower_cost", ref=1e6)
            
        elif self.opt["merit_figure"] == "monopile_mass":
            wt_opt.model.add_objective("fixedse.monopile_mass", ref=1e6)

        elif self.opt["merit_figure"] == "monopile_cost":
            wt_opt.model.add_objective("fixedse.monopile_cost", ref=1e6)

        elif self.opt["merit_figure"] == "jacket_mass":
            wt_opt.model.add_objective("fixedse.jacket_mass", ref=1e6)

        elif self.opt["merit_figure"] == "structural_mass":
            if not self.modeling["flags"]["floating"]:
                wt_opt.model.add_objective("fixedse.structural_mass", ref=1e6)
            else:
                wt_opt.model.add_objective("floatingse.system_structural_mass", ref=1e6)

        elif self.opt["merit_figure"] == "hub_mass":
            wt_opt.model.add_objective("drivese.hub_system_mass", ref=1e5)

        elif self.opt["merit_figure"] == "nacelle_mass":
            wt_opt.model.add_objective("drivese.nacelle_mass", ref=1e6)

        elif self.opt["merit_figure"] == "nacelle_cost":
            wt_opt.model.add_objective("tcc.nacelle_cost", ref=1e6)

        elif self.opt["merit_figure"] == "platform_hull_mass":
            wt_opt.model.add_objective("floatingse.platform_hull_mass", ref=1e6)

        elif self.opt["merit_figure"] == "platform_mass":
            wt_opt.model.add_objective("floatingse.platform_mass", ref=1e6)

        elif self.opt["merit_figure"] == "platform_cost":
            wt_opt.model.add_objective("floatingse.platform_cost", ref=1e6)

        elif self.opt["merit_figure"] == "mooring_mass":
            wt_opt.model.add_objective("floatingse.mooring_mass", ref=1e4)

        elif self.opt["merit_figure"] == "mooring_cost":
            wt_opt.model.add_objective("floatingse.mooring_cost", ref=1e4)

        elif self.opt["merit_figure"] == "Cp":
            if self.modeling["flags"]["blade"]:
                wt_opt.model.add_objective("rotorse.rp.powercurve.Cp_regII", ref=-1.0)
            else:
                wt_opt.model.add_objective("rotorse.ccblade.CP", ref=-1.0)

        elif self.opt["merit_figure"] in ["turbine_cost", "turbine_capex"]:
            wt_opt.model.add_objective("tcc.turbine_cost_kW", ref=1e3)

        elif self.opt["merit_figure"] in ["bos", "bos_cost", "bos_capex"]:
            if self.modeling["flags"]["offshore"]:
                wt_opt.model.add_objective("orbit.total_capex_kW", ref=1e3)
            else:
                wt_opt.model.add_objective("landbosse.total_capex_kW", ref=1e3)

        elif self.opt["merit_figure"] == "inverse_design":
            wt_opt.model.add_objective("inverse_design.objective")

        else:
            raise ValueError("The merit figure " + self.opt["merit_figure"] + " is unknown or not supported.")

        return wt_opt
```

**Comment by ptrbortolotti** [comment]
by default a figure of merit gets minimized, but we want to maximize Cp and AEP

**Comment by ptrbortolotti** [comment]
> > Most likely your thrust and/or omega constraints are too tight and the optimizer can't satisfy them. Try turning the off (flag set to False) and rerun. Once the optimizer converges, check out the final values of thrust and omega and see how far they are from your target values. An additional complication is that WISDEM computes the rotor speed given the input tip speed ratio and maximum blade tip speed. your optimizer does not have direct control over omega, so enforcing such tight constraint will be problematic. it's a lot easier to set a priori your maximum blade tip speed for your desired omega rather than hoping that the optimizer converges to your target
> 
> Thank you, I hope you had a great Christmas. I'll try modifying the TSR and maxTS now. Do you know what might be a suitable range for tol and step_size? I saw examples where step_size varies from e-3 to e-6.

This goes down to the art of optimization, I would not worry about changing those settings for now. step size of 1e-6 is the default. when you have some noise in your figure of merit, enlarging the time step can help convergence

**Comment by WANG-KUI-TJU** [comment]
It seems that in the input file (e.g., 02_reference_turbines/brel5mw.yaml), the components-hub section does not define the mass and inertia of the hub. Similarly, the nacelle does not have mass and inertia.
```
    hub:
        cone_angle: 0.04363
        diameter: 3.0
        drag_coefficient: 0.5
        hub_material: cast_iron
        spinner_material: glassDB
        flange_t2shell_t: 4.0
        flange_OD2hub_D: 0.5
        flange_ID2OD: 0.8
        hub_blade_spacing_margin: 1.2
        hub_stress_concentration: 2.5
        n_front_brackets: 3
        n_rear_brackets: 3
        clearance_hub_spinner: 0.75 #0.5
        spin_hole_incr: 1.2
        pitch_system_scaling_factor: 0.54
        spinner_gust_ws: 70.0
```
 However, I noticed that in the output file, there is this output:
```
        elastic_properties_mb:
            system_mass: 74380.12869676958
            system_inertia: [814844.3691271197, 511312.1079480642, 511312.1079480642, 0.0, 0.0, 0.0]
```
Neither [WindIO](https://windio.readthedocs.io/en/latest/source/hub.html) nor [input](https://wisdem.readthedocs.io/en/master/docstrings/wisdem_inputs.html) provides explanations for these parameters.
How are these values calculated?
