### ISSUE TITLE
How to address the issue of the V-T curve being shifted to the left?

### ISSUE THREAD

**Issue by WANG-KUI-TJU** [WISDEM/WISDEM#594]
## Description
I'm sorry to bother you again. Recently, while optimizing a new wind turbine, I encountered an issue. Although I can fit the thrust values well with the target turbine, the peak thrust always shifts to the left. For example, the target turbine (16 MW) reaches a maximum thrust of 2300 kN at 12 m/s, but no matter how I adjust MaxTS or TSR, I can't achieve this target. In several recent attempts, the maximum thrust occurs around 10.5 m/s. I've tried relaxing constraints and switching reference turbines (15 MW and 22 MW), but nothing works. Additionally, when I aim for a rated wind speed of 12 m/s, the thrust is always much less than 2300 kN. If it exceeds 2300 kN, I can adjust the peaking percent. What should I do?
## Thoughts and Questions
- Should I also make the 'airfoil_position' labels a design variable?
- I also tried modifying the precone angle (4 degrees/5 degrees) and tilt angle (4 degrees/6 degrees), but it didn't significantly improve the results.”
- Using the reference_axis to change the blade prebend seems like an option, but I haven't tried it yet.
- It seems that both the `z` and  `hub_diameter` affect the `rotor_diameter`, so they aren't independent variables, right? In the program, is it hub_diameter + 2z = rotor_diameter?
- "What other design variables can I try modifying to address the issue of the V-T curve being shifted to the left?(L/D?c_d?z?rotor_diameter?cone?hub_diameter?uptilt?)
```
design_variables:
    blade:
        aero_shape:
            twist: {flag: true, n_opt: 10, max_decrease: 0.08726, max_increase: 0.08726, index_start: 2, index_end: 10, cap_twist_root: 0.349, inverse: false, inverse_target: max_efficiency}
            chord: {flag: true, n_opt: 10, max_decrease: 0.5, max_increase: 1.1, index_start: 3, index_end: 10}
            af_positions: {flag: false, af_start: 4}
            rthick: {flag: false, n_opt: 30, max_decrease: 0.5, max_increase: 1.5, index_start: 0, index_end: 8}
            L/D: {flag: false, n_opt: 30, max_decrease: 0.5, max_increase: 1.5, index_start: 0, index_end: 8}
            c_d: {flag: false, n_opt: 8, max_decrease: 0.5, max_increase: 1.5, index_start: 0, index_end: 8}
            stall_margin: {flag: false, n_opt: 8, max_decrease: 0.5, max_increase: 1.5, index_start: 0, index_end: 8}
            z: {flag: false, n_opt: 3, lower_bound: -1.0, upper_bound: 1.0}
        structure: []
        n_opt_struct: [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30]
        layer_index_opt: []
    rotor_diameter: {flag: false, minimum: 0.0, maximum: 0.0}
    control:
        tsr: {flag: false, minimum: 0.0, maximum: 0.0}
    hub:
        cone: {flag: false, lower_bound: 0.0, upper_bound: 0.0}
        hub_diameter: {flag: false, lower_bound: 0.0, upper_bound: 30.0}
    drivetrain:
        uptilt: {flag: false, lower_bound: 0.0, upper_bound: 0.0}
        overhang: {flag: false, lower_bound: 0.1, upper_bound: 0.1}
```

![V-T curve being shifted to the left](https://github.com/user-attachments/assets/5dcbdbe9-611d-409d-9f77-c21d0b6de942)

## The following is my optimization settings file

```
general:
    folder_output: E:\Turbine\WISDEM\Opt_process\Case_3\out
    fname_output: blade_out
design_variables:
    blade:
        aero_shape:
            twist:
                flag: True
                n_opt: 8
                inverse: False
                inverse_target: 'stall_margin'
                max_decrease: 0.08722222222222221
                max_increase: 0.08722222222222221
                index_start: 2
                index_end: 8
                cap_twist_root: 0.349
            chord:
                flag: True  
                n_opt: 10 
                max_decrease: 0.3
                max_increase: 1.5
                index_start: 1
                index_end: 9

# figure of merit
merit_figure: AEP

# constraints
constraints:
    blade:
        chord:
            flag: True 
            max: 8.0
        chord_slope:
            flag: True 
        stall:
            flag: True # Constraint on minimum stall margin
            margin: 0.12 # Value of minimum stall margin in [rad]
    user:
      - name: rotorse.rp.powercurve.rated_T
        lower: [2300000]
        upper: [2400000]
        ref: [2300000]

      
# driver
driver:
    optimization:
        flag: True         
        tol: 1.e-2    
        max_iter: 100        
        solver: SLSQP       
        step_size: 1.e-5  
        form: forward       

recorder:
    flag: True              
    file_name: log_opt.sql  

```
I eagerly anticipate your esteemed reply and assistance！

**Comment by gbarter** [comment]
One suspicion is that the open-source airfoils, and their polars, that are used in the reference turbine fall a bit short compared to commercial state–of-the-art.  So, the aerodynamic performance using the open-source airfoils might always lag that of their commercial equivalents.  However, your plot shows a bit higher discrepancy than I would have expected.  To test it out, I would suggest lowering the value for your stall margin from 0.12 radians (nearly 7 deg!) to something more like 0.035 (2 deg).

Also tagging @ptrbortolotti in case he has other insights.

**Comment by ptrbortolotti** [comment]
I have the feeling that your rotor performance is off. What's your power coefficient? It might be too low. You can try to follow example 3a https://wisdem.readthedocs.io/en/master/examples/03_blade/tutorial.html
I often optimize Cp instead of AEP and I set twist to follow the inverse design approach described in this publication: https://iopscience.iop.org/article/10.1088/1742-6596/1618/4/042016/meta
Let us know!

**Comment by WANG-KUI-TJU** [comment]
> I have the feeling that your rotor performance is off. What's your power coefficient? It might be too low. You can try to follow example 3a https://wisdem.readthedocs.io/en/master/examples/03_blade/tutorial.html I often optimize Cp instead of AEP and I set twist to follow the inverse design approach described in this publication: https://iopscience.iop.org/article/10.1088/1742-6596/1618/4/042016/meta Let us know!

I'm not sure if the Cp is too low; it does seem a bit strange(Compared to the IEA 15MW and 22MW, it's not smooth enough.). The maximum Electrical Cp is in the range of (0.40, 0.44).I think the power coefficient provided by the manufacturer is problematic. They claim it can reach Cp = 0.46 near the cut-in wind speed.I haven't reviewed your paper in detail yet. I will try using Cp as the objective according to the paper and your suggestions.

![Image](https://github.com/user-attachments/assets/d27a88a2-32ef-42a6-91c3-62da2be1df9f)

**Comment by ptrbortolotti** [comment]
Ok your Cp is actually not too bad. Now my next question is about thrust: could it be that the target thrust includes the rotor weight? Out of WISDEM you are currently extracting aerodynamic thrust alone...

**Comment by WANG-KUI-TJU** [comment]
> Ok your Cp is actually not too bad. Now my next question is about thrust: could it be that the target thrust includes the rotor weight? Out of WISDEM you are currently extracting aerodynamic thrust alone...

your words was like a light bulb went off in my head. I once made a mistake on this issue, so I particularly remember this Rate_T. However, I remembered it incorrectly; it represents aerodynamic thrust, not the total rotor thrust...

**Comment by WANG-KUI-TJU** [comment]
## description
Good morning, esteemed professor. I have readjusted the value of Rated_T, and it is now entirely aerodynamic thrust. However, I've encountered a new issue: although I can meet the optimization requirements (Rated_V = 11 m/s, Rated_T = 2000 kN), I found that the chord and twist are quite peculiar and not smooth.I have encountered this issue before. I usually make slight adjustments to the constraints to achieve a reasonable smoothness. I've tried some solutions.

![Image](https://github.com/user-attachments/assets/102b4eba-dc9d-4d9f-aaec-f1e34b8deb7f)

![Image](https://github.com/user-attachments/assets/c8b8cd5b-615b-44d9-9040-a95ae765da3a)
## Thoughts and Questions
- I tried reducing the maximum increase and decrease for the chord, for example, setting `max_increase` to 1.2 and `max_decrease` to 0.8.I believe the solution space shouldn't be very large. An overly broad design range might lead it to settle on an unreasonable chord length.I don't know if this is the right thing to do?
- I increased n_op of chord. I think increasing `n_opt` might add more design variables,  it could make the chord smoother.Do you have any suggestions for the number of `n_opt`? For example, how many meters per `n_opt`?
- I tried the method from your paper, which involves adding a $C_m$ constraint and then using inverse design for the twist. I'm currently testing this approach. I'm not sure if my analysis YAML is correct?
## The following is my optimization settings file
```
general:
    folder_output: E:\Turbine\WISDEM\Opt_process\case_6.1\out
    fname_output: blade_out

design_variables:
    blade:
        aero_shape:
            twist:
                flag: False
                n_opt: 10
                inverse: True
                inverse_target: 'stall_margin'
                max_decrease: 0.08722222222222221
                max_increase: 0.08722222222222221
                index_start: 2
                index_end: 9
                cap_twist_root: 0.349
            chord:
                flag: True  
                n_opt: 20
                max_decrease: 0.8
                max_increase: 1.2
                index_start: 2
                index_end: 19

# figure of merit
merit_figure: Cp

# constraints
constraints:
    blade:
        chord:
            flag: True 
            max: 6.8
        chord_slope:
            flag: True 
        stall:
            flag: True 
            margin: 0.09 
        moment_coefficient: {flag: true, min: 0.15, max: 0.17}
    user:
      - name: rotorse.rp.powercurve.rated_T
        lower: [2000000]
        upper: [2400000]
        ref: [2300000]
      - name: rotorse.rp.powercurve.rated_V
        lower: [12.0]
        upper: [13.0]
        ref: [12.5]
            
# driver
driver:
    optimization:
        flag: True         
        tol: 1.e-3   
        max_iter: 100        
        solver: SLSQP       
        step_size: 1.e-6  
        form: forward       

recorder:
    flag: True              
    file_name: log_opt.sql  
```
