### ISSUE TITLE
Interpreting output thickness of tower and monopile

### ISSUE THREAD

**Issue by hishamtariq19** [WISDEM/WISDEM#639]
I am re-designing the tower and monopile of IEA-15MW-RWT in WISDEM, at various water depths and then plan to run OpenFAST simulations. While interpreting the output values of wall thickness along the height, I believe I am making a mistake because thickness between two points of an element along the height should be constant.

Is it possible to get any guidance on how to plot or consider outer diameter/wall thickness along the height of the monopile and tower from outputs excel file (tower_monopile_opt.xlsx) or from tower_monopile_opt.yaml?

**Comment by gbarter** [comment]
This is a topic that arises with some regularity and we have taken played with various approaches with the reference turbines.  If you look back in the Github file history, you will actually see a version of the 15-MW tower with many more data points to more clearly articulate a piecewise-constant thickness profile to reflect the manufacturing from constant-thickness steel plates.  We moved away from that because an argument was made that the reference turbines should not presuppose a manufacturing method and the general [windio](https://github.com/IEAWindSystems/windIO) input parameterization supports descriptions of linearly varying thickness sections.

Within WISDEM, we enforce a piecewise-constant thickness profile at [this line](https://github.com/WISDEM/WISDEM/blob/master/wisdem/commonse/cylinder_member.py#L371) of code.  So, with the following geometry yaml file:
```
 tower:
        outer_shape_bem:
            reference_axis:
                z:
                    grid: [0.0, 0.25, 0.50, 0.75, 1.0]
                    values: [10.0, 35.0, 60.0, 85.0, 110.0]
            outer_diameter:
                grid: [0.0, 0.25, 0.50, 0.75, 1.0]
                values: [10.0, 9.0, 8.0, 7.0, 6.0]
        internal_structure_2d_fem:
            layers:
               -  name: tower_wall
                  material: steel
                  thickness:
                      grid: [0.0, 0.25, 0.50, 0.75, 1.0]
                      values: [0.04, 0.035, 0.03, 0.025, 0.02]
```

WISDEM would model 4 segments.  The first would be between 10-35m in height, have a linearly tapering diameter from 10->9m, and have a constant thickness at 0.0375.  The second would be between 35-60m in height, have a linearly tapering diameter from 9->8m, and have a constant thickness at 0.0325.  And so on.  Other codes that use windIO may not interpret the thickness in the same way though.

The WISDEM plotting script [here](https://github.com/WISDEM/WISDEM/blob/master/wisdem/postprocessing/compare_designs.py#L386) also ensures that the plotting is done with a piecewise-constant depiction.  This is accessed with the `compare_designs` script.
